### ISSUE TITLE
Issues with findOptions()

### ISSUE THREAD

**Issue by dpvc** [limefrogyank/siunitx-pcc#1]
The function

https://github.com/limefrogyank/siunitx-pcc/blob/51e6c1e4d8e9429ee7451ffe2176db45501f6dbf/src/options/options.ts#L27-L47

will not find some options strings properly.  In particular, if the string includes macros like `\{`, `\}` or `\]`, then the function will likely not be able to locate the proper end of the options properly.  For example,

``` latex
\num[input-close-uncertainty = \}]{9.99(9\}}
```

is valid (but silly) in LaTeX, but produces the error `Could not find closing ']' for argument to \num` in MathJax.

The comment before the function says `Needed a new version of TexParser.GetBrackets because it wanted to parse the internal macros automatically`, but that is misleading.  The `GetBrackets()` method does take control sequences into account when it is looking for the closing `]`, if that's what you mean by "parsing", but that is necessary, as illustrated by the example above.

I would recommend using `GetBrackets()`.  It looks like you could just use

``` js
export function findOptions(parser: TexParser): Partial<IOptions> {
  return optionStringToObject(parser.GetBrackets(parser.currentCS));
}
```

This allows the example above to work.

**Comment by limefrogyank** [comment]
Thanks for this.  I believe when I started that I wasn't sure how to use the method properly...

**Comment by dpvc** [comment]
Thanks for looking into thee issues I've posted.  I still have some more to do, and some are more complicated, so I hope they are helpful to you.  Let me know if there are questions or concerns about what I suggest.  I hope you know they are all meant as constructive suggestions, not criticisms.  You have done a lot of hard work, here, clearly!
