### ISSUE TITLE
Don't set `data-semantic` attributes yourself (these are generated by SRE)

### ISSUE THREAD

**Issue by dpvc** [limefrogyank/siunitx-pcc#10]
You should not set `data-semantic` attributes yourself, as they are maintained by SRE.  So 

https://github.com/limefrogyank/siunitx-pcc/blob/51e6c1e4d8e9429ee7451ffe2176db45501f6dbf/src/siunitx.ts#L111

should not include the attributes list.

**Comment by limefrogyank** [comment]
This might have been before I understood the difference between mathspeak and clearspeak.  Not sure why I did this...
