### ISSUE TITLE
Some issues with generateNumberMapping

### ISSUE THREAD

**Issue by dpvc** [limefrogyank/siunitx-pcc#11]
I'm a little confused by the regular expression at

https://github.com/limefrogyank/siunitx-pcc/blob/51e6c1e4d8e9429ee7451ffe2176db45501f6dbf/src/numMethods.ts#L166

It seems to be intended to determine if a string is non-empty (i.e., has at least one control sequence or non-space character).  But the matching for control sequences isn't correct, since a control sequence is either (1) a `\` followed by one or more alphabetic characters (only a-z and A-Z), or a single non-alphabetic character.  Your match is against a string of characters other than `\`, which is more than is allowed.  That makes it hard for you to find the end of the control sequence, and you require either a space, another `\` or the end of the string to follow the control sequence.

A regular expresion that matches valid control sequences or single characters is `/\\(?:[a-zA-Z]+|[\uD800-\uDBFF].|.)|[\uD800-\uDBFF].|[^\s\\]/g`.  This handles multi-character Unicode glyphs, not just those in Unicode Plane 0.

Note that if you used `string.match(regex)` where `regex` has the `/g` option, you get back an array of all the matches rather than just a single match, which you get from `regex.exec(string)`.  So rather than

https://github.com/limefrogyank/siunitx-pcc/blob/51e6c1e4d8e9429ee7451ffe2176db45501f6dbf/src/numMethods.ts#L167-L169

it would be more efficient to do

``` js
        (options.inputComparators.match(matchMacrosOrChar) || []).forEach(c => parseMap.set(c, parseComparators);
```

rather than performing the `regex.exec()` over and over.

Note, however, that there is no error reported for when `\` is at the end of the string, and so is not a valid control sequence (it will be ignored by this regular expression).  So you might want to check for a final `\` that is not preceded by an even number of `\` and give an error in that case.  A regex like `/(?:^|[^\\])(?:\\\\)*\\$/` should do the job.

Since you have 9 `while` statements where 8 of them all work the same way, but with different names, you could use a loop over an array of the names to reduce the redundancy.  Something like

``` js
for ([key, method] of [
  ['inputComparators', parseComparators],
  ['inputSigns', parseSigns],
  ['inputDigits', parseDigits],
  ['inputDecimalMarkers', parseDecimals],
  ['inputOpenUncertainty', parseOpenUncertainty],
  ['inputCloseUncertainty', parseCloseUncertainty],
  ['inputUncertaintySigns', parseUncertaintySigns],
  ['inputExponentMarkers', parseExponentMarkers],
  ['inputIgnore', parseIgnore]
] as [keyof options, CharNumFunction][]) {
  const option = options[key];
  if (option.match(/(?:^|[^\\])(?:\\\\)*\\$/)) {
    throw new TexError('BadOptionChars', 'Invalid control sequence at the end of the %1 option', key);
  }
  (option.match(matchMacrosOrChar) || []).forEach(c => {
    if (parseMap.has(c) && key === 'inputUncertaintySigns') {
      const firstFunc = parseMap.get(c) as CharNumFunction;
      const innerMap = new Map<string, CharNumFunction>();
      innerMap.set('inputSigns', firstFunc);
      innerMap.set('inputUncertaintySigns', parseUncertaintySigns);
      parseMap.set(c, innerMap);
    } else {
      parseMap.set(c, method);
    }
  });
}
```

might do the trick.

**Comment by limefrogyank** [comment]
This is a good one.  Thanks
