### ISSUE TITLE
Comments on displayOutputMml()

### ISSUE THREAD

**Issue by dpvc** [limefrogyank/siunitx-pcc#15]
The `displayOutputMml()` function returns an array of `MmlNodes`, which are eventually pushed onto either another array or appended to a parent HTML node somewhere.  But MathJax already has a means of handling a group of `MmlNodes` via a single `MmlNode`:  the `inferredMrow` node type.  This can have any number of children, and when it is pushed onto a TeX parser via `parser.Push()`, or appended to another MmlNode via `node.appendChild()`, the inferred mrow is removed and its children are pushed or appended.  So you don't have to mailing logic yourself for handling the difference between a single `MmlNode` and an array of them, you can just assume everything is a single `MmlNode`, and use an inferred mrow to hold multiple ones in the cases that need them.  So, for example, instead of

https://github.com/limefrogyank/siunitx-pcc/blob/51e6c1e4d8e9429ee7451ffe2176db45501f6dbf/src/numDisplayMethods.ts#L525-L526

you could just use

``` js
        let rootNode = parer.create('node', 'inferredMrow', []);
        let currentNode = rootNode;
```

and then do `currentNode.appendChild(node)` instead of `rootNodes.push(node)`.  The main function would return `MmlNode` rather than `MmlNode[]`, and then functions like

https://github.com/limefrogyank/siunitx-pcc/blob/51e6c1e4d8e9429ee7451ffe2176db45501f6dbf/src/siunitx.ts#L24-L30

could just be

``` js
const methodMap: Record<string, (parser: TexParser) => void> = {
    '\\num': (parser: TexParser): void => {
        const node = processNumber(parser);
        parser.Push(node);
    },
```

like all the others in `siunitx.ts`.

This simplifies the two places you have code like

https://github.com/limefrogyank/siunitx-pcc/blob/51e6c1e4d8e9429ee7451ffe2176db45501f6dbf/src/numDisplayMethods.ts#L539-L543

which can just become

``` js
                currentNode.appendChild(prefix);
```

-----

You can also simplify

https://github.com/limefrogyank/siunitx-pcc/blob/51e6c1e4d8e9429ee7451ffe2176db45501f6dbf/src/numDisplayMethods.ts#L527-L533

and combine it with the `rootNode` definition as follows:

``` js
        const color = options.numberColor || options.color;
        const rootNode = parser.create('node', color ? 'mrow' : 'inferredMrow, [], color ? {mathcolor: color} : {});
```

and then there is no need for `currentNode`.

-----

In the lines

https://github.com/limefrogyank/siunitx-pcc/blob/51e6c1e4d8e9429ee7451ffe2176db45501f6dbf/src/numDisplayMethods.ts#L536-L538

there is no guarantee that `prefix` is an `<mo>` node.  Your current implementation allows multiple characters in `num.prefix`, in which case `prefix` will be an inferred mrow, and even if you restrict `num.prefix` to a single prefix (as the LaTeX version seems to), since the user can specify the allowed prefix characters, there is no guarantee that they will produce `mo` elements (e.g., they could be letters, so are `mi` nodes).

If might be better to use

``` js
                const prefix = (new TexParser('{' + num.prefix + '}', GlobalParser.stack.env, GlobalParser.configuration)).mml();
```

instead, since the braces will cause MathJax to not put spacing around the prefix (it will be treated as a TeX `ORD` atom).  That way, you don't have to worry about `lspace` and `rspace` yourself.

-----

Taking all that into account, the function could become

``` js
export function displayOutputMml(num: INumberPiece, parser: TexParser, options: IOptions): MmlNode {
        const color = options.numberColor || options.color;
        const rootNode = parser.create('node', color ? 'mrow' : 'inferredMrow, [], color ? {mathcolor: color} : {});
        if (num.prefix !== '') {
                const prefix = (new TexParser('{' + num.prefix + '}', GlobalParser.stack.env, GlobalParser.configuration)).mml();
                rootNode.appendChild(prefix);
        }
        rootNode.appendChild(displayNumberMml(num, parser, options));
        return rootNode;
}
```

provided `displayNumberMml()` returns a single `MmlNode` using the same approach as used here.  I will discuss `displayNumberMml()` in a separate issue.

**Comment by limefrogyank** [comment]
Made a bunch of changes to remove passing plain arrays of `MmlNode` to just a single `MmlNode` of kind 'inferredMrow'.  Also, removed `displayNumber` method in favor of using the `displayNumberMml` method.  This forced me to rewrite a bunch of functions including `displayAngle` which is now `displayAngleMml`.  

https://github.com/limefrogyank/siunitx-pcc/commit/12c4960425a3a49bb16a8579840150a192ca8d8e

Also, part of this is in preparation to remove `GlobalParser`.  That required me to pass along the current instance `TeXParser` into a lot more functions... hence the rewrite.

**Comment by dpvc** [comment]
Yes, this kind of change does have ripple effects throughout the code.  Thanks for being willing to make the changes.  I think that will make things easier in the long run.

**Comment by limefrogyank** [comment]
pretty sure this is all handled now.  No more returning arrays of nodes.  No more GlobalParser
