### ISSUE TITLE
Use prefixed package data

### ISSUE THREAD

**Issue by dpvc** [limefrogyank/siunitx-pcc#17]
Because the `parseOptions.packageData` is shared among all packages, it is usually best to put your data in a sub-object identified by your package name.  That is, the two maps at

https://github.com/limefrogyank/siunitx-pcc/blob/03fcce23b21261b1fd205c3637e62fa9223481d1/src/siunitx.ts#L168-L169

probably should be stored in a `siunitx` object, as in 

``` js
    jax.parseOptions.packageData.set('siunitx', {
        [UserDefinedUnitsKey]: new Map<string,string>(),
        [UserDefinedUnitOptionsKey]: new Map<string,string>()
    );
```

(and the look-ups for these would need to be adjusted to match).  While the keys probably would not cause a conflict with other packages, it is still best practice to separate your data from everyone else's.

**Comment by limefrogyank** [comment]
Ah, sorry, I think I missed that part in a prior issue.

**Comment by dpvc** [comment]
No problem.  I do put several into one tracker, which probably isn't a good idea.
