### ISSUE TITLE
Issues with findInnerText() and addSpacing()

### ISSUE THREAD

**Issue by dpvc** [limefrogyank/siunitx-pcc#18]
As you mention, the function 

https://github.com/limefrogyank/siunitx-pcc/blob/03fcce23b21261b1fd205c3637e62fa9223481d1/src/numDisplayMethods.ts#L18-L28

makes the assumption that there is only one child node to any node, and that is not a very good assumption.  The function can be both simplified and made to work on element with more than one child using the following:

``` js
export function findInnerText(node: MmlNode): string {
    return node.walkTree((node: MmlNode, data: {text: string}) => {
        if (node.isToken) {
            data.text += node.getText();
        }
    }, {text: ''}).text;
}
```

You may have to cast `node` as `(node as AbstractMmlTokenNode)` for `getString()` for Typescript.

-----

I understand what you are trying to do in these lines

https://github.com/limefrogyank/siunitx-pcc/blob/03fcce23b21261b1fd205c3637e62fa9223481d1/src/numDisplayMethods.ts#L31-L37

but there are some issues to consider.  First, you `spacerMap` makes the assumption that the macros have their default values, and that the user hasn't modified any of them.  For example, if you did

``` html
$$\let\,=\ \num{12345678}$$
```

the spaces between blocks of three would be full-sized spaces (from `\ `), not thin spaces (from `\,`).  Granted, this is not very likely, but it is a difference from actual LaTeX that can be avoided (see below).

The second issue is with the processing of elements that are **not** in `spacerMap`, which assumes that the spacer will produce some text, whereas it could produce just MathML elements like `mspace`.  E.g., if `group-separator = \>` (`\>` is a spacing macro not in your list), then there will be no text returned from `findInnerText()`.

Finally, since `spacerMap` is an `Object`, it inherits all the default object properties, like `toString`, `valueOf`, `constructor`, etc., so if the user did `group-separator = toString`, for example, `mmlSpacer` would end up being a function, not a string, and will end up inserting `function toString() { [native code] }` into the number (and `mmlSpacer.length` will not be the right value).

I think the solution to all of these is to not use `spaceMap` at all, and instead always parse the separator, and use a modified version of the `walkTree()` function above to use the `mspace` node `width` attributes to select the unicode character to use.  For example, 

``` js

const spaceMap: Record<string, string> = {
    '1em': '\u2001',
    '2em': '\u2001\u2001',
    '.167em': '\u2006',
    '.222em': '\u2005',  // U+2005 is actually .25em
    '.278em': '\u2004',  // U+2004 is actually .333em
};

export function findInnerText(node: MmlNode): string {
    return node.walkTree((node: MmlNode, data: {text: string}) => {
        if (!node.isToken) return;
        if (node.isKind('mspace')) {
          const w = node.attributes.getExplicit('width');
          if (spaceMap.hasOwnProperty(w)) {
            data.text += spaceMap[w];
          }
        } else {
            data.text += node.getText();
        }
    }, {text: ''});
}
```

and then replace

https://github.com/limefrogyank/siunitx-pcc/blob/03fcce23b21261b1fd205c3637e62fa9223481d1/src/numDisplayMethods.ts#L31-L37

by just the two lines

``` js
	const spacerNode = (new TexParser(spacer, parser.stack.env, parser.configuration)).mml();
	mmlSpacer = findInnerText(spacerNode);
```

This will allow you to handle redefinitions of the spacing macros, as well as macros defined in terms of `space` nodes.  The handing of the `width` parameters could be made more sophisticated, but this is probably sufficient for now.  Note that I don't use U+2009, since that is font-dependent, whereas U+2006 is the six-per-em space, or 3/18 em, guaranteed.

Of course, in LaTeX, you can use something like `group-spacer = +^2` if you wanted to, but since you are going to put the number into an `mn` node, you can't have superscripts or other non-text node into that, so this is something you won't be able to support.  Of course, it is not likely to come up, so no big deal.  Similarly, `group-spacer = +` is allowed, and you would get the `+` character, but the spacing would be different, since in actual LaTeX, there would be spaces around the `+`, but not here.  I suppose one could look for `mo` nodes and add the spacing they would normally produce (or the closest to it we can get), but it is probably not worth it.  It might also be worth generating a warning or even an error in the case that you have a non-token node, so that `+^2` or `\frac{1}[2}` would produce an indication that these are not supported.

-----

These lines

https://github.com/limefrogyank/siunitx-pcc/blob/03fcce23b21261b1fd205c3637e62fa9223481d1/src/numDisplayMethods.ts#L39-L40

don't take Unicode into account other than Plane 0.  For example, if someone wanted to use the numbers from the Math Alphanumeric block (starting at a U+1D400) by using `input-digits = 𝟘𝟙𝟚𝟛𝟜𝟝𝟞𝟟𝟠𝟡`, for example, this wouldn't count the digits properly, since each of these takes two UTF-16 characters.  One solution would be to use

``` js
        const arr = [...text];
        if (arr.length >= minimum) {
```

since `...text` splits the text into actual unicode characters (which may be two UTF-16 characters wide).  I would rename `arr` to something like `digits` to be more descriptive.

-----

The rest of the `addSpace()` function,

https://github.com/limefrogyank/siunitx-pcc/blob/03fcce23b21261b1fd205c3637e62fa9223481d1/src/numDisplayMethods.ts#L41-L58

can be made more efficient in several ways.  First, the `fluidCount` is not used on the first pass through either loop, and is always set to the same value within the loop, so you can make `fluidCount` a constant and set it outside the loop, right after defining `firstCount`.

Second, since `addSpacing()` is only used in four places (all in this file), and you always pass a value to `digitGroupFirstSize` and `digitGroupOtherSize`, these parameters should not be optional, and you can skip the test if they are undefined.  (If they aren't given explicitly in the bracket options, they will have the default `-1` value).

Third, rather than redefining the `text` string over and over again, you could use the `arr` (or `digits` array itself and insert the separator string into that, then use `digits.join('')` at the end to build your final string.  This avoids creating substrings and merging them into new strings multiple times (splicing a new entry into an array just needs to move the pointers to the strings in that array, and arrays are expanded to include extra elements so that they don't have to be reallocated if more elements are added, so modifying the array in this way is more efficient).  This also avoids the need for the `adjusted` variable.

Finally, you can collapse the two loops into a single one by setting up the starting position and increment value as variables based on the value of `reverse`.  For example, the complete function could be:

``` js
function addSpacing(
        parser: TexParser,
        text: string,
        digitGroupSize: number,
        minimum: number,
        spacer: string,
        reverse: boolean,
        digitGroupFirstSize: number,
        digitGroupOtherSize: number
) {
	const spacerNode = (new TexParser(spacer, parser.stack.env, parser.configuration)).mml();
	mmlSpacer = findInnerText(spacerNode);
        const digits = [...text];
        if (digits.length >= minimum) {
                const firstSize = (digitGroupFirstSize !== -1 ? digitGroupFirstSize : digitGroupSize);
                const groupSize = (digitGroupOtherSize !== -1 ? digitGroupOtherSize : digitGroupSize);
                const [start, size] = (reverse ? [firstSize, groupSize + 1] : [digits.length - firstSize, -groupSize]);
                for (let i = start; i >= 0 && i < digits.length; i += size) {
                    digits.splice(i, 0, mmlSpacer);
                }
        }
        return digits.join('');
```

The `start` and `size` are set to either go from left to right (taking the spliced separator into account) for reversed processing, or from right to left for normal processing.

**Comment by limefrogyank** [comment]
Thanks for this.  I noticed that using `.167em` didn't work because it was using leading zeros: `0.167em`

I ended up adding both to the map, however, that makes me wonder:  are commas ever allowed in place of decimals for this type of attribute?  i.e. `0,167em`  

I would have assumed no, but since this isn't javascript exactly, I'm not sure now...

**Comment by dpvc** [comment]
You are right, I wasn't paying close enough attention to the values (just the actual decimals).  I don't think that `0,167em` will work.  Just tested it, and no, it is taken as an invalid attribute value.  So you don't have to worry about that.

As you can see, I don't always fully test the code samples, so be aware that some adjustments may be needed.  They should be morally right, if not explicitly right.  :-)

**Comment by dpvc** [comment]
I also don't think you need to keep the `'.167em'` versions, since you are really only looking for the results of the `\,`, `\:`, `\;`, etc. macros, and since they have the 0, really no need to keep the other values, I think.  But I suppose it doesn't hurt.
