### ISSUE TITLE
Build script builds all of MathJax unnecessarily

### ISSUE THREAD

**Issue by dpvc** [limefrogyank/siunitx-pcc#2]
The `build` script in the `package.json` file ends up building all of MathJax for no reason (`mathjax-full` includes all the needed files that come from the build process).

One solution would be to add the `--no-subdirs` option to the `makeAll` command in the `build script`  That will just build the `siunitx` extension.

**Comment by limefrogyank** [comment]
Oh, this is excellent.  I knew the exact point in the entire build process where the siunitx extension was done and just canceled the rest, but this is still much faster.  Thanks.

**Comment by limefrogyank** [comment]
[commit ](https://github.com/limefrogyank/siunitx-pcc/commit/5e716f4581efaf1f6a42e9b3f88d927df584e1f7) fixes this
