### ISSUE TITLE
Suggestions for `displayNumberMml()`

### ISSUE THREAD

**Issue by dpvc** [limefrogyank/siunitx-pcc#20]
The lines

https://github.com/limefrogyank/siunitx-pcc/blob/70ca5c4581c2760b7aac5ca5a9fb0416665ab6e5/src/numDisplayMethods.ts#L244-L255

Always sets the number to the negative color, even when it is not negative.  That can be corrected and simplified to

``` js
        const rootNode = parser.create('node', 'mrow');
        if (num.sign === '-' && options["negative-color"]) {
                rootNode.attribute.set('mathcolor', options["negative-color"]);
        }
```

and then use `rootNode` in place of `currentNode` throughout the rest.

-----

I think that there is a problem with 

https://github.com/limefrogyank/siunitx-pcc/blob/70ca5c4581c2760b7aac5ca5a9fb0416665ab6e5/src/numDisplayMethods.ts#L258-L273

If both `bracket-negative-numbers` and `print-implicit-plus` are true and `num.sign` is empty (i.e., the number is positive), you will not get a leading plus sign, as you would in actual LaTeX.  This is due to the processing of `print-implicit-plus` in the `else` clause above.  I think they need to be separate if-then statements.

Also, lines 264 to 271 can be collapsed to

``` js
        if (num.sign || options["print-implicit-plus"]) {
                const sign = parser.create('token', 'mo', { rspace: "0em", lspace: "0em" }, num.sign || '+');
                currentNode.appendChild(sign);
        }
```

-----

In

https://github.com/limefrogyank/siunitx-pcc/blob/70ca5c4581c2760b7aac5ca5a9fb0416665ab6e5/src/numDisplayMethods.ts#L279-L280

should `num.exponent === '1'` be `num.exponent === '0'`, as the comment implies?

Also, in other places (e.g. line 292), you use `+(value) === 0` rather than `value === '0'` to test for a zero value.  Do you want to do that here, and other places where you have `... === '0'`?

-----

In line

https://github.com/limefrogyank/siunitx-pcc/blob/70ca5c4581c2760b7aac5ca5a9fb0416665ab6e5/src/numDisplayMethods.ts#L281

since `numberString` is known to be empty at this point, why not just assign it directly, rather than use `+=`?

Similarly for lines 286 and 289.

-----

In line

https://github.com/limefrogyank/siunitx-pcc/blob/70ca5c4581c2760b7aac5ca5a9fb0416665ab6e5/src/numDisplayMethods.ts#L284-L284

you use `num.fractional` rather than `num-fractional !== ''` as you have everywhere else.  I prefer the usage without the equality check against an empty string, so I'd recommend using `num.fractional` (or `!!num.fractional` if you prefer) here and elsewhere.  Similarly, `!num.fractional` in place of `num.fractional === ''`.

-----

In the lines

https://github.com/limefrogyank/siunitx-pcc/blob/70ca5c4581c2760b7aac5ca5a9fb0416665ab6e5/src/numDisplayMethods.ts#L305-L306

note that `uncertaintyNode` can be `null` (when the user supplies an invalid `uncertainty-mode`), and so you may be appending a `null` child, which will cause a failure when you call `appendChild()` on it.  You might use

``` js
                currentNode.appendChild(uncertaintyNode || parser.create('node', 'inferredMrow'));
```

of do the `appendChild()` inside an if-then.

-----

In lines

https://github.com/limefrogyank/siunitx-pcc/blob/70ca5c4581c2760b7aac5ca5a9fb0416665ab6e5/src/numDisplayMethods.ts#L313-L318

the two if-thens should be combined into one, as in

``` js
        if (options["bracket-negative-numbers"] && num.sign === '-') {
                const rightBracket = parser.create('token', 'mo', {}, ')');
                currentNode.appendChild(rightBracket);
        }
```

I'm wondering if you should add `stretchy: false` in the `{}` for this and the open parenthesis above?  This is how `(` and `)` are usually treated in TeX, whereas your current versions are like `\left(...\right)`.

**Comment by limefrogyank** [comment]
> 
> Also, in other places (e.g. line 292), you use `+(value) === 0` rather than `value === '0'` to test for a zero value. Do you want to do that here, and other places where you have `... === '0'`?

This is tricky.  I'm switching the whole number check to a number.  That way entering `00.1` will evaluate to `0.1` or `.1` with `print-zero-integer` set to `false`.  I don't think there's a use for many leading zeros to the left of a decimal point.  However, we can't do this for the fractional part.  So, I need to be selective about where to compare it as a number vs a string.  

I may need to revisit this choice.

**Comment by limefrogyank** [comment]
Related to fixing these issues:

WIthin `createQuantityProductMml` function of qtyMethods.ts, having an empty `quantity-product` created an undefined `quantityProductNode`.  (Example `\qty[quantity-product = ]{2.67}{\farad}`)

Since there is still an understood operator between the value and unit, just shortened to nothing, I chose to create an empty `mo` mathml node rather than remove the `mo` node completely.

**Comment by limefrogyank** [comment]
Added `stretchy:false` to the options for brackets.  Not sure if this makes a difference, but I'll take your word for it...
