### ISSUE TITLE
Issue with optionStringToObject and processOptions

### ISSUE THREAD

**Issue by dpvc** [limefrogyank/siunitx-pcc#7]
There are several redundancies within these functions.  First off, they both do essentially the same thing, just one going to a map, and one to an object.  You could reduce the redundancy by using one to produce the other.  For example

``` js
function optionStringToObject(optionString: string): Partial<IOptions> {
  return Object.fromEntries(processOptions(siunitxDefaults, optionString).entries());
}
```

In addition, the lines

https://github.com/limefrogyank/siunitx-pcc/blob/51e6c1e4d8e9429ee7451ffe2176db45501f6dbf/src/options/options.ts#L115-L130

appears a second time as 

https://github.com/limefrogyank/siunitx-pcc/blob/51e6c1e4d8e9429ee7451ffe2176db45501f6dbf/src/options/options.ts#L149-L165

so these should probably be folded into a service routine that is used in both places.

-----

There are a number of inconsistencies between how LaTeX processes arguments and how these two functions do it.

For example, in LaTeX, braces are removed if they appear around the key as well as the value.  For example,

``` latex
\num[{tight-spacing}={true}]{1.23e3}
```

is valid in LaTeX, while this will fail in your code.  The first reason it fails is that you remove the opening a closing braces, even though they are not paired, in

https://github.com/limefrogyank/siunitx-pcc/blob/51e6c1e4d8e9429ee7451ffe2176db45501f6dbf/src/options/options.ts#L176-L178

This should only be done when the braces are actually paired with each other, and it should only be done for the outermost braces (additional braces, even if paired, are **not** removed by LaTeX).

Another reason it fails is that you don't test for braces in the key, and you test for braces in the value only if the value doesn't contains a control sequence.  LaTeX removes always removes them, so in

``` latex
$$\num[exponent-product={\bf x}]{1.23e3}$$
```

for example, the braces are removed and the x *and the exponent* are both in bold.

You also potentially remove braces that are not paired, as in 

``` latex
\num[exponent-product={x}y{z}]{1.23e3}
```

you will end up with `exponent-product` being `x}y{z`, which leads to an error message about an extra `}`.

Finally, you do not report errors for undefined options, or bad option values, as LaTeX would.  For example

``` latex
\num[xyz = 1]{123} \num[tight-spacing=xyz]{123}
```

will report the unknown option for the first `\num` call, and report an invalid value for the second one.  You code accepts them both.

In any case, MathJax already has functions for parsing a LaTeX key-value string, with optional error reporting, and you should probably take advantage of those rather than roll your own.  That way, your extension will be consistent with MathJax's other packages, and if there are any problems, they can be fixed in one central location, rather than in several separate packages.  It also handles control sequences properly, and doesn't require them to be followed by a space, which isn't required by actual LaTeX.

The `keyvalueOptions()` function from `ParseUtil.ts` does the parsing that you are doing here, so that is the function you could use.  The main difference is that only boolean types are translated from strings, (not numbers as in your case), so you would need to post-process the option object to convert the numeric values.  Also, there is no type checking, so you would want to do that in post-processing as well.

So something like:

``` js
import ParseUtil from 'mathjax-full/js/ParseUtil.js';

export function processOptions(globalOptions: IOptions, optionString: string): Map<string, any> {
  const optionObject = ParseUtil.keyvalueOptions(optionString, globalOptions, true);
  const options = new Map<string, any>();
  for (let [key, value] of Object.entries(optionObject)) {
    const type = typeof globalOptions[key];
    if (typeof value !== type) {
      if (type === 'number' && value.match(/^[-+]?(?:\d+(?:\.\d*)?|\.\d+)(?:e[-+]\d+)?$/)) {
        value = parseFloat(value);
      } else {
        throw new TexError('siunitx:badvalue', 'Key %1 accepts only values of type %2', key, type);
      }
    }
    options.set(key, value);
  }
  return options;
}
```

(untested code, so you may need to do a little fiddling).

While I was testing your parsing, and preparing to recommend `keyvalueOptions()`, I discovered that `keyvalueOptions()` also has some parsing inconsistencies, so doesn't get all the examples above correct, either.  I will be making a PR to correct them, but I still recommend using `keyvalueOptions()` rather than your own version so that the parsing will be consistent across packages, and so that fixes like the ones I will be making will fix *all* packages at once.  I am also considering adding the type checking/conversion that you should be doing as well.  That would mean you could just do

``` js
import ParseUtil from 'mathjax-full/js/ParseUtil.js';

export function processOptions(globalOptions: IOptions, optionString: string): Map<string, any> {
  return new Map<string, any>(Object.entries(ParseUtil.keyvalueOptions(optionString, globalOptions, true)));
}
```

**Comment by limefrogyank** [comment]
This has been painful so far, but nearly done.  You mentioned that `keyvalOptions` has some problems, too.  I'm finding that an option defined like this doesn't work anymore: `\ang[number-angle-product = \,]{2.67}`

I've had to change it to `\ang[number-angle-product = {\,}]{2.67}` to make it work.  Was the former a bad LaTeX format?  I had assumed it should work, but maybe the comma is an issue and it needs the braces.

**Comment by limefrogyank** [comment]
Another one that doesn't work:
`\num[uncertainty-mode=compact, output-open-uncertainty=[, output-close-uncertainty=], uncertainty-separator=\,]{1.234(5)}`

Works if changed to:
`\num[uncertainty-mode=compact, output-open-uncertainty={[}, output-close-uncertainty={]}, uncertainty-separator={\,}]{1.234(5)}`

**Comment by dpvc** [comment]
Yes, `keyvalOptions` fails to handle backslashes properly in its current form.  I have made a PR that fixes it, but that will be in v4.  I may back port to v3 after v4 is out.

In the meantime, use the `{\,}` solution for now, and I'll put together a file with the v4 `keyvalOptions` that you can use temporarily.

As for the example with `[` and `]`, I did not expect that to work in actual LaTeX, but it does.  Apparently, the LaTeX3 implementation of finding the closing `]` for optional arguments not only matches braces, but also brackets, so the ']' in `output-close-uncertainty=]` closes the `[` in `output-open-uncertainty=[`.  That isn't the case in `keyvalOptions`, and so the optional argument is closed at the ']' in `output-close-uncertainty=]` instead.  I will need to fix that in the v4 `keyvalueOptions` as well.  Note that if you switched the order to be

```
\num[uncertainty-mode=compact, output-close-uncertainty=], output-open-uncertainty=[, uncertainty-separator=\,]{1.234(5)}
```

then it fails in LaTeX as well.

**Comment by limefrogyank** [comment]
I'll mention one last scenario:  using the LaTeX space `\ ` (blank space after backslash) no longer works as an option.  I can't seem to get it to work with curly braces, either.  (Using `keyvalOptions`)

Ex:  `\qty[quantity-product = {\ }]{2.67}{\farad}`

**Comment by dpvc** [comment]
Thanks, I'll need to fix that one, too.

**Comment by dpvc** [comment]
OK, I've put together a patch file that you can use to fix the `keyvalOptions()` problems.  

[patch.ts.gz](https://github.com/limefrogyank/siunitx-pcc/files/13844775/patch.ts.gz)

Put it in your source hierarchy somewhere and then use

``` js
import './patch.js';
```

in `siunuitx.ts` (add in whatever path is needed to get to it).  This should patch the `keyvalOptions()` function to the v4 version.  (I haven't included the type-checking for the allowed options, but if you want that, I can patch that in, too.  It hasn't yet been reviewed and merged into the v4 development branch.)

You can use `keyvalOptions(text, allowed, true, true)` to get the options given in the `text` string, with the `allowed` object giving the names of the options that are allowed (e.g., `{option1: 1, option2: 1}`, etc.).  When the type-checking is added, you would use type type definitions instead of `1` for the values of the option keys.  (More on that if you want the type checking.)

In order to have the balanced brackets in `GetBracket()`, use `GetBracket(parser.currentCS, default, true)`, where `default` is the default value (you can use `null` or `undefined` for no default value).

Let me know if you have any trouble with that.

**Comment by limefrogyank** [comment]
The patch is working on my build, but I couldn't get a way to make typings work for the new prototype functions.  If I'm understanding the typescript docs correctly, I cannot augment a class with an interface if the class is a default export.  Oh well, not a big deal... I just converted to `any` and used it javascript style.

The "back-slash space" options work without curly braces now.  However, one option fails to work and it's in the siunitx pdf as an example:
```
\qty{2.67}{\farad} \\
\qty[quantity-product = \ ]{2.67}{\farad} \\
\qty[quantity-product = ]{2.67}{\farad}
2.67 F
2.67 F
2.67F
```
The third option where the space between quantity and unit is completely removed cannot be parsed and generates the error:  `Cannot read properties of null (reading 'isInferred')`

**Comment by dpvc** [comment]
> The third option where the space between quantity and unit is completely removed cannot be parsed and generates the error

The problem is unrelated to `keyvalOptions()`, and is in the function

https://github.com/limefrogyank/siunitx-pcc/blob/03fcce23b21261b1fd205c3637e62fa9223481d1/src/qtyMethods.ts#L226-L240

In the case that `quantity-product` is empty, this function returns `null`, which eventually gets appended to a parent node in 

https://github.com/limefrogyank/siunitx-pcc/blob/03fcce23b21261b1fd205c3637e62fa9223481d1/src/qtyMethods.ts#L124-L131

even if it is `null`.  It is that null child that is causing the failure (probably in `appendChild()`, since that checks if the child node is inferred, and it can't do that if it is null).  I suppose `appendChild()` should check for that, but there are a couple of other ways to handle that.

First, you could have `separateUncertaintyUnitsMmlMap()` only append the `quantityProduct` if it is not null.

Alternatively, you could have `createQuantityProductMml()` not return `null` but rather return an empty inferred mrow instead (since appending that to a parent node will end up appending nothing).

I suspect there are other places that you might run into the same problem, where you either return `null` explicitly (as in this case), or where `(new TexParser(tex, ...).mml())` returns `null` when `tex` is an empty string.  To overcome this, you might make a utility function like the following

``` js
latex2mml(parser: TexParser, tex: string): MmlNode {
  return (new TexParser(tex, parser.stack.env, parser.configuration)).mml() || parser.create('node', 'interredMrow');
}
```

and then use that wherever you are using `new TexParser(...)` now.  This guarantees that you always get an MmlNode, and using the result in `parser.Push(mml)` or `node.appendChild(mml)` should do nothing if `mml` is an empty inferred row.  This also reduces the redundant code, making your package slightly smaller.  Then you just have to look for the places like `createQuantityProductMml()` that could return `null` for other reasons.

**Comment by limefrogyank** [comment]
Seems to be done.
